### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, open '*filepath*' at Error (native)

### ISSUE THREAD

**Issue by ChapDaddy65** [jamen/gulp-pug#1]
Here's what I have in my gulpfile to process Pug:

```javascript
gulp.task('build-html', function () {
    'use strict';
    return gulp.src('src/pug/index.pug')
        .pipe(pug({pretty: true}))
        .pipe(gulp.dest('public'));
});
```

I have tried multiple iterations of the destination folder `./public` `./public/` `/public/` `/public` , etc. and I always get this error:

```
Error: EISDIR: illegal operation on a directory, open 'C:\...\project-root\public\index.html'
    at Error (native)
```

What am I doing wrong?

**Comment by jamen** [comment]
Hey, thanks for reporting this.

I don't think you are doing anything wrong, seems to be a bug with gulp-pug.  I'll look into it now.  :)

**Comment by jamen** [comment]
I coped your gulpfile, and mimicked the directories...  I get no error and everything seems to work fine.

**Comment by ChapDaddy65** [comment]
It was an error on my end... I didnt realize that gulp created an folder named `index.html` *facepalm*
Everything works now.

Sorry & Thank you.
