### ISSUE TITLE
gulp-data cannot work well with gulp-pug

### ISSUE THREAD

**Issue by Dafrok** [jamen/gulp-pug#10]
Following the document of gulp-data, I tried to inject some variables into my pug template, but nothing happend.No data was injected and no errors in console.
Then I use 'gulp-jade' instead of 'gulp-pug', the problem has gone.

pug template:
```jade
div= foo
```

gulpfile.js
```javascript
const data = require('gulp-data')
const pug = require('gulp-pug')
// const pug = require('gulp-jade') // If I use this, everything will work well.
gulp.task('pug', e => gulp.src('./src/pug/index.pug')
  .pipe(data(function (file) {
    return {foo: 'bar'}
  }))
  .pipe(pug())
  .pipe(gulp.dest('./dist/'))
)
```

**Comment by jamen** [comment]
I will take a look, thanks.

**Comment by jamen** [comment]
This will be introduced in the next version (after I fix the other issues).  Thank you.  :)

**Comment by jamen** [comment]
Released that new version a little while ago by the way.  Should work now.

**Comment by Dafrok** [comment]
Thank you for your great work!
