### ISSUE TITLE
Quits out of gulp-build on error, although plumber is used

### ISSUE THREAD

**Issue by herrbischoff** [jamen/gulp-pug#12]
Excerpt from my `gulpfile`:

```coffee
gulp.task 'pug', ->
  return gulp.src paths.pug.input
    .pipe plugins.plumber
      errorHandler: plugins.notify.onError "Error: <%= error.message %>"
    .pipe plugins.pug
      pretty: true
    .pipe gulp.dest paths.pug.output
```

Whenever `pug` encounters an error, the whole build is quit.

```
[22:16:57] Starting 'pug'...
/Users/[REDACTED]/node_modules/pug-lexer/index.js:53
    throw err;
    ^

Error: /Users/[REDACTED]/src/pug/index.pug:5:25
    3|   head
    4|     meta(charset="utf-8")
  > 5|     metaname="viewport" content="width=device-width")
-------------------------------^
    6|     title srcset test
    7|     script document.createElement( "picture" );
    8|     script(src="javascript/bundle.min.js" async)

Syntax Error: Unexpected token
  at makeError (/Users/[REDACTED]/node_modules/pug-error/index.js:32:13)
[...]
```

The expected behavior due to `plumber` would be to output the error but not to interrupt the build process. I set up the error processing this way so I wouldn't have to restart `gulp` on every little hickup.

Am I doing something fatally wrong or is this related to how this plugin (mis)behaves?

**Comment by jamen** [comment]
I do not have experience with plumber, but `gulp-pug` passes on errors normally (with `PluginError` in the callback).

Perhaps it is because it also always passes on the HTML too:
```javascript
callback(error, html);
```

Not sure how plumber detects errors, but maybe it is not working correctly because the contents exist...  Maybe this would be more suitable:
```javascript
callback(error, error ? html : null);
```

This is probably ultimately better behavior anyways.  Seems more logical.

**Comment by jamen** [comment]
Also worth mentioning that `PluginError` will be deprecated, but after looking the gulp issues it doesn't seem like there is a viable alternative quite yet.

**Comment by jamen** [comment]
Oh wait, now relooking at this issue, it's because `pug` throws an error that I'm not catching.

**Comment by jamen** [comment]
Released a new version.  It should work now.

**Comment by herrbischoff** [comment]
Indeed, it works a expected now. Thank you very much!
