### ISSUE TITLE
pipe(pug().on('error', handle(e)) not work?

### ISSUE THREAD

**Issue by kassiansun** [jamen/gulp-pug#20]
gulp.watch will not watch any more when errors occurred, not like gulp-webpack and other gulp plugins

**Comment by jamen** [comment]
Thanks for reporting.  I'll look into the issue.

**Comment by jamen** [comment]
This appears to be the expected behavior:
```javascript
.pipe(through.obj(function(x, y, callback) {
  callback(new Error('Foobar!'))
}))
// Never called:
.pipe()
```
I was able to listen to errors on `pug()`:
```javascript
.pipe(pug().on('error', err => ...))
// Never called:
.pipe()
```

Could you post code?  I might be able to reproduce better, if this actually is an issue.

**Comment by kassiansun** [comment]
```
gulp.task('pug', [], () =>
  gulp.src(paths.pug)
  .pipe(pug({
    pretty: true,
  }).on('error', e => console.log(e)))
  .pipe(gulp.dest(paths.www))
);
```
then

```
gulp.watch(paths.pug, ['pug']);
```

gulp.watch should rebuild the pugs when the syntax error fixed, but it didn't

**Comment by kassiansun** [comment]
This is the gulp's behavior and should be handled by gulp-plumber, sorry to disturb..

**Comment by jamen** [comment]
No problem.  Glad you figured out your issue.
