### ISSUE TITLE
blacklist / possible collaboration

### ISSUE THREAD

**Issue by phated** [jamen/gulp-pug#22]
This module is being blacklisted due to being a duplicate of https://github.com/phated/gulp-jade - we have a pull request open to handle the jade -> pug rename that we will be merging.  Would you like to take over gulp-jade instead?

**Comment by jamen** [comment]
This is my first project where I actually maintain something people consistently use and report directly to, so I think it is more valuable for me to keep it than to hand it over...  It's unfortunate that you're blacklisting it just because it is a "duplicate"...  I'm only 15, so I think it is a small experience that helps me understand how to maintain a project.

Thanks for the offer, but I think I'll decline.  Sorry for stealing it from you, but I would be happy to add you as a collaborator to this repo instead.

**Comment by phated** [comment]
Oh, I meant that I would transfer it to you, but it would maintain all the support people have come to expect from gulp-jade.  I'm happy handing it off to you.

**Comment by jamen** [comment]
Oh, sorry for misunderstanding.

I think that it is probably best to have the support be equal, but the thing is, I like having this repository on my profile.  I think I'm more interested in making a compatible API so people can transition easier...  I was originally going to do that, but I didn't want to just copy your code.

**Comment by phated** [comment]
@jamen I'm still confused.  You can have the gulp-jade (probably renamed to gulp-pug) repository on your profile (because it would be transferred to you) and you can make changes as you see fit.

**Comment by phated** [comment]
@jamen it would even come with the stars/watchers/etc that gulp-jade already has

**Comment by jamen** [comment]
Oh okay,  I wasn't aware you were going to transfer it.  That would be awesome!  Thank you.  :)

**Comment by jamen** [comment]
So what does it entail?

**Comment by phated** [comment]
@jamen I can transfer gulp-jade to your "jamen" account and it will add me as a collaborator, you can then change the name, etc.  I will add you to the gulp-jade npm package also.

**Comment by jamen** [comment]
Okay, that sounds good.  I can go ahead and rename this one and deprecate.

**Comment by phated** [comment]
perfect, I sent the transfer request

**Comment by jamen** [comment]
Thank you :o

I went ahead and added you as a collaborator to the gulp-pug package.

**Comment by jamen** [comment]
@phated: One more question.  How am I supposed to handle the licensing?  Do I leave it as your name because it is all of your work, or do I switch it to me?

**Comment by phated** [comment]
Lodash does it by mentioning the previous license/licensor - see https://github.com/lodash/lodash/blob/master/LICENSE#L3-L4
