### ISSUE TITLE
Not able to include .pug files 

### ISSUE THREAD

**Issue by lawrence79** [jamen/gulp-pug#8]
I'm trying to import _header.pug and _footer.pug into _layout.pug but every time I run my gulp task. 
```
var gulp = require('gulp');
var plumber = require('gulp-plumber');
var pug = require('gulp-pug');



gulp.task('pug', function() {
    return gulp.src(['src/views/*.pug', '!./src/views/_*'])
        .pipe(plumber())
        .pipe(pug({
            pretty: true
        }))
        .pipe(gulp.dest('dist'));
});
```

I get `TypeError: Cannot read property 'replace' of undefined`

If I rename them to `.jade` it works fine.

**Comment by jamen** [comment]
Hello, thanks for reporting.  Did you install `pug` alongside `gulp-pug`?  You should get a unmet `peerDependencies` warning.
```
npm install --save pug@latest
```
`gulp-pug` is a wrapper over the version of pug you want to use, so it is not included.

**Comment by lawrence79** [comment]
That worked! Thanks very much @jamen .

**Comment by jamen** [comment]
No problem. :D
